### ISSUE TITLE
Timeout auditing netlify page

### ISSUE THREAD

**Issue by maguayo** [jakejarvis/lighthouse-action#24]
This is the error I have:

```
##[warning]Unexpected input(s) 'url', 'netlify_site', valid inputs are ['entryPoint', 'args']
Run jakejarvis/lighthouse-action@master
/usr/bin/docker run --name c20127cec257b1b34d1a9759181d61ee670b_9a4d29 --label 87c201 --workdir /github/workspace --rm -e INPUT_URL -e INPUT_NETLIFY_SITE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/XXXXX-frontend/XXXXX-frontend":"/github/workspace" 87c201:27cec257b1b34d1a9759181d61ee670b
* Beginning audit of https://deploy-preview-197--XXXXXXXXX.netlify.app ...

Wed, 15 Jul 2020 07:34:36 GMT ChromeLauncher No debugging port found on port 9222, launching a new Chrome.
Wed, 15 Jul 2020 07:34:36 GMT ChromeLauncher Waiting for browser...
Wed, 15 Jul 2020 07:34:37 GMT ChromeLauncher Waiting for browser.....
Wed, 15 Jul 2020 07:34:37 GMT ChromeLauncher Waiting for browser.....✓
Wed, 15 Jul 2020 07:34:37 GMT config:warn IFrameElements gatherer requested, however no audit requires it.
Wed, 15 Jul 2020 07:34:37 GMT config:warn InspectorIssues gatherer requested, however no audit requires it.
Wed, 15 Jul 2020 07:34:37 GMT status Connecting to browser
Wed, 15 Jul 2020 07:34:37 GMT status Resetting state with about:blank
Wed, 15 Jul 2020 07:34:37 GMT status Benchmarking machine
Wed, 15 Jul 2020 07:34:38 GMT status Initializing…
Wed, 15 Jul 2020 07:34:38 GMT status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, IFrameElements, MainDocumentContent, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility, TraceElements, InspectorIssues, SourceMaps
Wed, 15 Jul 2020 07:34:38 GMT status Resetting state with about:blank
Wed, 15 Jul 2020 07:34:38 GMT status Setting up network for the pass trace
Wed, 15 Jul 2020 07:34:38 GMT status Cleaning browser cache
Wed, 15 Jul 2020 07:34:38 GMT method <= browser ERR:error Audits.enable 
Wed, 15 Jul 2020 07:34:38 GMT status Beginning devtoolsLog and trace
Wed, 15 Jul 2020 07:34:38 GMT status Loading page & waiting for onload
Wed, 15 Jul 2020 07:35:23 GMT Driver:warn Timed out waiting for page load. Checking if page is hung...
Wed, 15 Jul 2020 07:35:24 GMT Driver:warn Page appears to be hung, killing JavaScript...
Wed, 15 Jul 2020 07:35:54 GMT status Disconnecting from browser...
Wed, 15 Jul 2020 07:35:54 GMT ChromeLauncher Killing Chrome instance 31
Wed, 15 Jul 2020 07:35:54 GMT GatherRunner disconnect:error read ECONNRESET
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)
LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

And this is my config:
```
name: Audit pull request
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://XXXXX.com/'
        netlify_site: 'XXXXX.netlify.app'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
```

I've checked if the preview link (https://deploy-preview-197--XXXXXXXXX.netlify.app) is working and it is.

**Comment by aidenmitchell** [comment]
I have the same issue, but it's not a Netlify site.

**Comment by maguayo** [comment]
@aidenmitchell Have you found a solution?

**Comment by aidenmitchell** [comment]
Unfortunately, I have not.
