### ISSUE TITLE
Allocated time exceeded

### ISSUE THREAD

**Issue by filiptronicek** [jakejarvis/lighthouse-action#29]
When running the action, this error occurs
``` 
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:413:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by aheil** [comment]
I do experience the same issue here. 

There is a lighthouse issue (https://github.com/GoogleChrome/lighthouse/issues/10996) which points to https://github.com/GoogleChrome/lighthouse/issues/6512. 

This might be helpful to figure out the cause for this issue.
